CREATE OR REPLACE TRIGGER OWNER_ODONTO.TRG_PACIENTES_BIU
BEFORE INSERT OR UPDATE ON OWNER_ODONTO.PACIENTES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ID_PACIENTE IS NULL THEN
            :NEW.ID_PACIENTE := OWNER_ODONTO.SEQ_PACIENTES.NEXTVAL;
        END IF;
        IF :NEW.DATA_CADASTRO IS NULL THEN
            :NEW.DATA_CADASTRO := SYSDATE;
        END IF;
    END IF;
END TRG_PACIENTES_BIU;
/
