CREATE OR REPLACE TRIGGER OWNER_ODONTO.TRG_BLOQUEIA_DELETE_AUDITORIA
BEFORE UPDATE OR DELETE ON OWNER_ODONTO.HISTORICO_AUDITORIA
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20099, 'Violacao de Compliance: A tabela de auditoria e estritamente imutavel e append-only.');
END TRG_BLOQUEIA_DELETE_AUDITORIA;
/
