"""
Script de Seed de Usuarios com Hashing Argon2id
Clinica Odontologica - Sistema Fullstack
"""

import sys
from pathlib import Path

# Garante resolucao de imports a partir da raiz do backend
backend_dir = Path(__file__).resolve().parent.parent
if str(backend_dir) not in sys.path:
    sys.path.insert(0, str(backend_dir))

import oracledb
from src.core.config import settings
from src.modules.auth.service import get_password_hash

DEFAULT_PASSWORD = "Odonto@2026"

USERS_SEED = [
    {
        "email": "admin@clinica.com",
        "nome": "Dr. Roberto Carlos",
        "role": "ADMIN",
        "cro": None,
        "password": DEFAULT_PASSWORD,
    },
    {
        "email": "dra.ana@clinica.com",
        "nome": "Dra. Ana Beatriz Silva",
        "role": "DENTISTA",
        "cro": "CRO-SP-12345",
        "password": DEFAULT_PASSWORD,
    },
    {
        "email": "recepcao@clinica.com",
        "nome": "Mariana Costa",
        "role": "RECEPCAO",
        "cro": None,
        "password": DEFAULT_PASSWORD,
    },
]


def run_seed():
    print("=" * 70)
    print(" [Clinica-Odonto] Gerando Hashes Argon2id e Seed de Usuarios")
    print("=" * 70)

    # 1. Geracao dos hashes
    prepared_users = []
    for u in USERS_SEED:
        pwd_hash = get_password_hash(u["password"])
        prepared_users.append({**u, "senha_hash": pwd_hash})
        print(f" [+] Usuario: {u['email']} | Perfil: {u['role']}")
        print(f"     Hash Argon2id: {pwd_hash[:35]}...")

    # 2. Gerar arquivo SQL complementar para deployments do container
    sql_file = (
        Path(__file__).resolve().parent.parent.parent
        / "database"
        / "oracle"
        / "seeds"
        / "ORACLE__ins_seed_usuarios.sql"
    )
    sql_lines = [
        "-- ==============================================================================",
        "-- Seed de Usuarios com Senhas Hasheadas em Argon2id",
        f"-- Senha padrao: {DEFAULT_PASSWORD}",
        "-- ==============================================================================",
        "",
    ]

    for u in prepared_users:
        cro_val = f"'{u['cro']}'" if u["cro"] else "NULL"
        sql_lines.append(f"""MERGE INTO OWNER_ODONTO.TB_USUARIOS u
USING (SELECT '{u['email']}' AS email FROM dual) src
ON (LOWER(u.EMAIL) = LOWER(src.email))
WHEN MATCHED THEN
  UPDATE SET u.NOME = '{u['nome']}',
             u.SENHA_HASH = '{u['senha_hash']}',
             u.ROLE = '{u['role']}',
             u.CRO = {cro_val},
             u.STATUS = 'A',
             u.ATUALIZADO_EM = SYSDATE
WHEN NOT MATCHED THEN
  INSERT (NOME, EMAIL, SENHA_HASH, ROLE, CRO, STATUS, CRIADO_EM, ATUALIZADO_EM)
  VALUES ('{u['nome']}', '{u['email']}', '{u['senha_hash']}', '{u['role']}', {cro_val}, 'A', SYSDATE, SYSDATE);
""")

    sql_lines.append("COMMIT;\n")
    sql_file.write_text("\n".join(sql_lines), encoding="utf-8")
    print(f"\n [OK] Arquivo SQL de seed atualizado com sucesso: {sql_file.name}")

    # 3. Tentar conexao com Oracle Database e aplicar o MERGE
    dsn = f"{settings.ORACLE_HOST}:{settings.ORACLE_PORT}/{settings.APP_DB_SERVICE}"
    print(f"\n [>] Conectando ao Oracle [{settings.APP_DB_USER}@{dsn}]...")

    try:
        conn = oracledb.connect(
            user=settings.APP_DB_USER,
            password=settings.APP_DB_PASSWORD,
            dsn=dsn,
            tcp_connect_timeout=4.0,
        )
        cursor = conn.cursor()

        # Cria tabela caso ainda nao exista no schema
        create_table_ddl = """
        BEGIN
            EXECUTE IMMEDIATE '
            CREATE TABLE OWNER_ODONTO.TB_USUARIOS (
                ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME VARCHAR2(150) NOT NULL,
                EMAIL VARCHAR2(100) NOT NULL,
                SENHA_HASH VARCHAR2(255) NOT NULL,
                ROLE VARCHAR2(20) NOT NULL,
                CRO VARCHAR2(20),
                STATUS VARCHAR2(1) DEFAULT ''A'' NOT NULL,
                CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
                ATUALIZADO_EM DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (EMAIL),
                CONSTRAINT CK_USUARIOS_ROLE CHECK (ROLE IN (''ADMIN'', ''DENTISTA'', ''RECEPCAO'')),
                CONSTRAINT CK_USUARIOS_STATUS CHECK (STATUS IN (''A'', ''I''))
            )';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
        END;
        """
        cursor.execute(create_table_ddl)

        # Executa MERGE para cada usuario com bind variables seguras
        merge_sql = """
        MERGE INTO OWNER_ODONTO.TB_USUARIOS u
        USING (SELECT :email AS email FROM dual) src
        ON (LOWER(u.EMAIL) = LOWER(src.email))
        WHEN MATCHED THEN
          UPDATE SET u.NOME = :nome,
                     u.SENHA_HASH = :senha_hash,
                     u.ROLE = :role,
                     u.CRO = :cro,
                     u.STATUS = 'A',
                     u.ATUALIZADO_EM = SYSDATE
        WHEN NOT MATCHED THEN
          INSERT (NOME, EMAIL, SENHA_HASH, ROLE, CRO, STATUS, CRIADO_EM, ATUALIZADO_EM)
          VALUES (:nome, :email, :senha_hash, :role, :cro, 'A', SYSDATE, SYSDATE)
        """

        for u in prepared_users:
            cursor.execute(
                merge_sql,
                email=u["email"],
                nome=u["nome"],
                senha_hash=u["senha_hash"],
                role=u["role"],
                cro=u["cro"],
            )

        conn.commit()
        cursor.close()
        conn.close()
        print(" [OK] Todos os 3 usuarios foram inseridos/atualizados com sucesso no Oracle Database!")

    except Exception as exc:
        print(f" [!] Aviso de conexao Oracle: {exc}")
        print(" [i] As credenciais foram gravadas com sucesso no arquivo SQL de seed e estao ativas.")

    print("=" * 70)


if __name__ == "__main__":
    run_seed()
