CREATE TABLE OWNER_ODONTO.HISTORICO_AUDITORIA (
    ID_AUDITORIA NUMBER(15) NOT NULL,
    NOME_TABELA VARCHAR2(50) NOT NULL,
    ID_REGISTRO NUMBER(10) NOT NULL,
    ACAO VARCHAR2(10) NOT NULL,
    DATA_ACAO DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_DB VARCHAR2(50) NOT NULL,
    DADOS_ANTIGOS_JSON CLOB,
    DADOS_NOVOS_JSON CLOB,
    CONSTRAINT PK_HIST_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT CK_AUDITORIA_ACAO CHECK (ACAO IN ('INSERT', 'UPDATE', 'DELETE'))
);

COMMENT ON TABLE OWNER_ODONTO.HISTORICO_AUDITORIA IS 'Tabela de logs rastreaveis preenchida via Triggers para fins de seguranca e compliance.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.ID_AUDITORIA IS 'Identificador unico da trilha de auditoria.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.NOME_TABELA IS 'Nome da tabela que sofreu a modificacao.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.ID_REGISTRO IS 'ID (Chave Primaria) do registro na tabela afetada.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.ACAO IS 'Acao realizada (INSERT, UPDATE, DELETE).';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.DATA_ACAO IS 'Data e hora exata da alteracao.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.USUARIO_DB IS 'Usuario do banco de dados que efetuou a operacao.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.DADOS_ANTIGOS_JSON IS 'Estado do registro ANTES da alteracao (em JSON). Nulo em caso de INSERT.';
COMMENT ON COLUMN OWNER_ODONTO.HISTORICO_AUDITORIA.DADOS_NOVOS_JSON IS 'Estado do registro DEPOIS da alteracao (em JSON). Nulo em caso de DELETE.';
