CREATE TABLE OWNER_ODONTO.PROCEDIMENTOS (
    ID_PROCEDIMENTO NUMBER(10) NOT NULL,
    NOME_PROCEDIMENTO VARCHAR2(150) NOT NULL,
    DESCRICAO VARCHAR2(255),
    VALOR_BASE NUMBER(10,2) NOT NULL,
    ID_ESPECIALIDADE NUMBER(10) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_PROCEDIMENTOS PRIMARY KEY (ID_PROCEDIMENTO),
    CONSTRAINT FK_PROCED_ESPECIALIDADE FOREIGN KEY (ID_ESPECIALIDADE) REFERENCES OWNER_ODONTO.ESPECIALIDADES (ID_ESPECIALIDADE),
    CONSTRAINT CK_PROCEDIMENTOS_STATUS CHECK (STATUS IN ('A', 'I')),
    CONSTRAINT CK_PROCED_VALOR CHECK (VALOR_BASE >= 0)
);

COMMENT ON TABLE OWNER_ODONTO.PROCEDIMENTOS IS 'Catalogo de servicos e tratamentos oferecidos.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.ID_PROCEDIMENTO IS 'Identificador unico do procedimento.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.NOME_PROCEDIMENTO IS 'Nome curto do procedimento.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.DESCRICAO IS 'Descricao detalhada do que contempla o procedimento.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.VALOR_BASE IS 'Valor base de tabela cobrado pelo procedimento.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.ID_ESPECIALIDADE IS 'Especialidade na qual o procedimento se enquadra.';
COMMENT ON COLUMN OWNER_ODONTO.PROCEDIMENTOS.STATUS IS 'Status do registro: A - Ativo, I - Inativo.';
