CREATE TABLE OWNER_ODONTO.PRONTUARIO_ELETRONICO (
    ID_PRONTUARIO NUMBER(10) NOT NULL,
    ID_AGENDAMENTO NUMBER(10) NOT NULL,
    ID_PACIENTE NUMBER(10) NOT NULL,
    ID_DENTISTA NUMBER(10) NOT NULL,
    DATA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    ANAMNESE CLOB,
    DESCRICAO_CLINICA CLOB NOT NULL,
    ID_PROCEDIMENTO NUMBER(10) NOT NULL,
    VALOR_COBRADO NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_PRONTUARIO PRIMARY KEY (ID_PRONTUARIO),
    CONSTRAINT UK_PRONTUARIO_AGENDA UNIQUE (ID_AGENDAMENTO),
    CONSTRAINT FK_PRONTUARIO_AGENDA FOREIGN KEY (ID_AGENDAMENTO) REFERENCES OWNER_ODONTO.AGENDAMENTOS (ID_AGENDAMENTO),
    CONSTRAINT FK_PRONTUARIO_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES OWNER_ODONTO.PACIENTES (ID_PACIENTE),
    CONSTRAINT FK_PRONTUARIO_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES OWNER_ODONTO.DENTISTAS (ID_DENTISTA),
    CONSTRAINT FK_PRONTUARIO_PROCED FOREIGN KEY (ID_PROCEDIMENTO) REFERENCES OWNER_ODONTO.PROCEDIMENTOS (ID_PROCEDIMENTO),
    CONSTRAINT CK_PRONT_VALOR CHECK (VALOR_COBRADO >= 0)
);

COMMENT ON TABLE OWNER_ODONTO.PRONTUARIO_ELETRONICO IS 'Historico clinico executado durante as consultas.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ID_PRONTUARIO IS 'Identificador unico do prontuario.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ID_AGENDAMENTO IS 'Vinculo 1:1 com o agendamento correspondente.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ID_PACIENTE IS 'Paciente atendido (redundancia util para analises).';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ID_DENTISTA IS 'Dentista responsavel pelo atendimento.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.DATA_REGISTRO IS 'Data e hora do preenchimento do prontuario.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ANAMNESE IS 'Descricao de queixas, alergias e estado geral do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.DESCRICAO_CLINICA IS 'Detalhes clinicos dos procedimentos realizados e observacoes do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.ID_PROCEDIMENTO IS 'Procedimento principal realizado.';
COMMENT ON COLUMN OWNER_ODONTO.PRONTUARIO_ELETRONICO.VALOR_COBRADO IS 'Valor final registrado para a consulta/procedimento.';
