CREATE TABLE OWNER_ODONTO.DENTISTAS (
    ID_DENTISTA NUMBER(10) NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    CRO VARCHAR2(20) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    ID_ESPECIALIDADE_PRINCIPAL NUMBER(10) NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_DENTISTAS PRIMARY KEY (ID_DENTISTA),
    CONSTRAINT UK_DENTISTAS_CRO UNIQUE (CRO),
    CONSTRAINT UK_DENTISTAS_CPF UNIQUE (CPF),
    CONSTRAINT FK_DENTISTAS_ESPECIALIDADE FOREIGN KEY (ID_ESPECIALIDADE_PRINCIPAL) REFERENCES OWNER_ODONTO.ESPECIALIDADES (ID_ESPECIALIDADE),
    CONSTRAINT CK_DENTISTAS_STATUS CHECK (STATUS IN ('A', 'I'))
);

COMMENT ON TABLE OWNER_ODONTO.DENTISTAS IS 'Cadastro de profissionais de odontologia da clinica.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.ID_DENTISTA IS 'Identificador unico do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.NOME IS 'Nome completo do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.CRO IS 'Conselho Regional de Odontologia do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.CPF IS 'Documento de pessoa fisica do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.ID_ESPECIALIDADE_PRINCIPAL IS 'Chave estrangeira vinculando a principal especialidade.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.TELEFONE IS 'Telefone de contato do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.EMAIL IS 'Email profissional do dentista.';
COMMENT ON COLUMN OWNER_ODONTO.DENTISTAS.STATUS IS 'Status do registro: A - Ativo, I - Inativo.';
