CREATE TABLE OWNER_ODONTO.PACIENTES (
    ID_PACIENTE NUMBER(10) NOT NULL,
    NOME VARCHAR2(150) NOT NULL,
    CPF VARCHAR2(14) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR2(20),
    EMAIL VARCHAR2(100),
    ENDERECO VARCHAR2(255),
    DATA_CADASTRO DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_PACIENTES PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT UK_PACIENTES_CPF UNIQUE (CPF),
    CONSTRAINT CK_PACIENTES_STATUS CHECK (STATUS IN ('A', 'I'))
);

COMMENT ON TABLE OWNER_ODONTO.PACIENTES IS 'Informacoes dos clientes/pacientes da clinica.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.ID_PACIENTE IS 'Identificador unico do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.NOME IS 'Nome completo do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.CPF IS 'Documento do paciente. Deve ser valido.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.DATA_NASCIMENTO IS 'Data de nascimento do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.TELEFONE IS 'Telefone de contato principal.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.EMAIL IS 'Email do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.ENDERECO IS 'Endereco residencial do paciente.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.DATA_CADASTRO IS 'Data de inclusao do registro no sistema.';
COMMENT ON COLUMN OWNER_ODONTO.PACIENTES.STATUS IS 'Status do registro: A - Ativo, I - Inativo.';
