CREATE TABLE OWNER_ODONTO.AGENDAMENTOS (
    ID_AGENDAMENTO NUMBER(10) NOT NULL,
    ID_PACIENTE NUMBER(10) NOT NULL,
    ID_DENTISTA NUMBER(10) NOT NULL,
    DATA_HORA_AGENDAMENTO DATE NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'AGENDADO' NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(255),
    OBSERVACAO VARCHAR2(500),
    CONSTRAINT PK_AGENDAMENTOS PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_AGENDAMENTOS_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES OWNER_ODONTO.PACIENTES (ID_PACIENTE),
    CONSTRAINT FK_AGENDAMENTOS_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES OWNER_ODONTO.DENTISTAS (ID_DENTISTA),
    CONSTRAINT CK_AGENDAMENTOS_STATUS CHECK (STATUS IN ('AGENDADO', 'CONFIRMADO', 'CANCELADO', 'REALIZADO'))
);

COMMENT ON TABLE OWNER_ODONTO.AGENDAMENTOS IS 'Controle de agenda, horarios e vinculo dentista/paciente.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.ID_AGENDAMENTO IS 'Identificador unico do agendamento.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.ID_PACIENTE IS 'Paciente agendado.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.ID_DENTISTA IS 'Dentista que ira atender.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.DATA_HORA_AGENDAMENTO IS 'Data e hora em que a consulta foi marcada.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.STATUS IS 'Status da consulta (AGENDADO, CONFIRMADO, CANCELADO, REALIZADO).';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.MOTIVO_CONSULTA IS 'Breve descricao do motivo da consulta.';
COMMENT ON COLUMN OWNER_ODONTO.AGENDAMENTOS.OBSERVACAO IS 'Anotacoes adicionais da recepcao.';
