CREATE TABLE OWNER_ODONTO.ESPECIALIDADES (
    ID_ESPECIALIDADE NUMBER(10) NOT NULL,
    NOME_ESPECIALIDADE VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(255),
    STATUS VARCHAR2(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_ESPECIALIDADES PRIMARY KEY (ID_ESPECIALIDADE),
    CONSTRAINT CK_ESPECIALIDADE_STATUS CHECK (STATUS IN ('A', 'I'))
);

COMMENT ON TABLE OWNER_ODONTO.ESPECIALIDADES IS 'Cadastro de especialidades odontologicas.';
COMMENT ON COLUMN OWNER_ODONTO.ESPECIALIDADES.ID_ESPECIALIDADE IS 'Identificador unico da especialidade.';
COMMENT ON COLUMN OWNER_ODONTO.ESPECIALIDADES.NOME_ESPECIALIDADE IS 'Nome da especialidade (ex: Ortodontia).';
COMMENT ON COLUMN OWNER_ODONTO.ESPECIALIDADES.DESCRICAO IS 'Descricao detalhada da especialidade.';
COMMENT ON COLUMN OWNER_ODONTO.ESPECIALIDADES.STATUS IS 'Status do registro: A - Ativo, I - Inativo.';
