-- Inserindo Especialidades
INSERT INTO OWNER_ODONTO.ESPECIALIDADES (ID_ESPECIALIDADE, NOME_ESPECIALIDADE, DESCRICAO, STATUS)
VALUES (OWNER_ODONTO.SEQ_ESPECIALIDADES.NEXTVAL, 'Ortodontia', 'Correcao da posicao dos dentes e dos ossos maxilares.', 'A');

INSERT INTO OWNER_ODONTO.ESPECIALIDADES (ID_ESPECIALIDADE, NOME_ESPECIALIDADE, DESCRICAO, STATUS)
VALUES (OWNER_ODONTO.SEQ_ESPECIALIDADES.NEXTVAL, 'Endodontia', 'Tratamento de canal, polpa dentaria e tecidos periapicais.', 'A');

INSERT INTO OWNER_ODONTO.ESPECIALIDADES (ID_ESPECIALIDADE, NOME_ESPECIALIDADE, DESCRICAO, STATUS)
VALUES (OWNER_ODONTO.SEQ_ESPECIALIDADES.NEXTVAL, 'Odontopediatria', 'Atendimento especializado para criancas.', 'A');

-- Inserindo Dentistas
INSERT INTO OWNER_ODONTO.DENTISTAS (ID_DENTISTA, NOME, CRO, CPF, ID_ESPECIALIDADE_PRINCIPAL, TELEFONE, EMAIL, STATUS)
VALUES (OWNER_ODONTO.SEQ_DENTISTAS.NEXTVAL, 'Dra. Ana Silva', 'CRO-SP-12345', '11122233344', 1, '11999998888', 'ana.silva@clinica.com', 'A');

INSERT INTO OWNER_ODONTO.DENTISTAS (ID_DENTISTA, NOME, CRO, CPF, ID_ESPECIALIDADE_PRINCIPAL, TELEFONE, EMAIL, STATUS)
VALUES (OWNER_ODONTO.SEQ_DENTISTAS.NEXTVAL, 'Dr. Roberto Carlos', 'CRO-SP-54321', '55566677788', 2, '11988887777', 'roberto.carlos@clinica.com', 'A');

-- Inserindo Pacientes
INSERT INTO OWNER_ODONTO.PACIENTES (ID_PACIENTE, NOME, CPF, DATA_NASCIMENTO, TELEFONE, EMAIL, ENDERECO, STATUS)
VALUES (OWNER_ODONTO.SEQ_PACIENTES.NEXTVAL, 'Joao Mendes', '12345678901', TO_DATE('15/05/1990', 'DD/MM/YYYY'), '11977776666', 'joao.mendes@email.com', 'Rua das Flores, 123', 'A');

-- Inserindo Procedimentos
INSERT INTO OWNER_ODONTO.PROCEDIMENTOS (ID_PROCEDIMENTO, NOME_PROCEDIMENTO, DESCRICAO, VALOR_BASE, ID_ESPECIALIDADE, STATUS)
VALUES (OWNER_ODONTO.SEQ_PROCEDIMENTOS.NEXTVAL, 'Manutencao Aparelho', 'Troca de borrachinhas e ajuste do fio.', 150.00, 1, 'A');

INSERT INTO OWNER_ODONTO.PROCEDIMENTOS (ID_PROCEDIMENTO, NOME_PROCEDIMENTO, DESCRICAO, VALOR_BASE, ID_ESPECIALIDADE, STATUS)
VALUES (OWNER_ODONTO.SEQ_PROCEDIMENTOS.NEXTVAL, 'Tratamento de Canal', 'Remocao do nervo e selamento.', 800.00, 2, 'A');

COMMIT;
