CREATE OR REPLACE VIEW OWNER_ODONTO.VW_AGENDA_DIARIA_DENTISTA AS
SELECT 
    d.NOME AS DENTISTA,
    d.CRO,
    e.NOME_ESPECIALIDADE,
    a.DATA_HORA_AGENDAMENTO,
    p.NOME AS PACIENTE,
    a.STATUS,
    a.MOTIVO_CONSULTA
FROM OWNER_ODONTO.AGENDAMENTOS a
JOIN OWNER_ODONTO.DENTISTAS d ON a.ID_DENTISTA = d.ID_DENTISTA
JOIN OWNER_ODONTO.ESPECIALIDADES e ON d.ID_ESPECIALIDADE_PRINCIPAL = e.ID_ESPECIALIDADE
JOIN OWNER_ODONTO.PACIENTES p ON a.ID_PACIENTE = p.ID_PACIENTE
WHERE TRUNC(a.DATA_HORA_AGENDAMENTO) = TRUNC(SYSDATE)
ORDER BY a.DATA_HORA_AGENDAMENTO;
