CREATE OR REPLACE VIEW OWNER_ODONTO.VW_HISTORICO_PRONTUARIO_PACIENTE AS
SELECT 
    p.NOME AS PACIENTE,
    p.CPF,
    pe.DATA_REGISTRO,
    d.NOME AS DENTISTA_ATENDENTE,
    pr.NOME_PROCEDIMENTO,
    pe.VALOR_COBRADO,
    pe.DESCRICAO_CLINICA
FROM OWNER_ODONTO.PRONTUARIO_ELETRONICO pe
JOIN OWNER_ODONTO.PACIENTES p ON pe.ID_PACIENTE = p.ID_PACIENTE
JOIN OWNER_ODONTO.DENTISTAS d ON pe.ID_DENTISTA = d.ID_DENTISTA
JOIN OWNER_ODONTO.PROCEDIMENTOS pr ON pe.ID_PROCEDIMENTO = pr.ID_PROCEDIMENTO
ORDER BY pe.DATA_REGISTRO DESC;
