-- Grants para aplicacao (DML e Execute)
GRANT EXECUTE ON OWNER_ODONTO.PKG_ATENDIMENTO_ODONTO TO RL_ODONTO_APP;
GRANT EXECUTE ON OWNER_ODONTO.PRC_AGENDAR_CONSULTA TO RL_ODONTO_APP;
GRANT EXECUTE ON OWNER_ODONTO.PRC_REGISTRAR_PRONTUARIO TO RL_ODONTO_APP;

GRANT INSERT, UPDATE, DELETE, SELECT ON OWNER_ODONTO.PACIENTES TO RL_ODONTO_APP;
GRANT INSERT, UPDATE, DELETE, SELECT ON OWNER_ODONTO.AGENDAMENTOS TO RL_ODONTO_APP;
GRANT INSERT, UPDATE, DELETE, SELECT ON OWNER_ODONTO.PRONTUARIO_ELETRONICO TO RL_ODONTO_APP;
GRANT INSERT, UPDATE, DELETE, SELECT ON OWNER_ODONTO.ODONTOGRAMA TO RL_ODONTO_APP;
GRANT INSERT, UPDATE, DELETE, SELECT ON OWNER_ODONTO.ODONTOGRAMA_PROCEDIMENTOS TO RL_ODONTO_APP;

GRANT SELECT ON OWNER_ODONTO.SEQ_PACIENTES TO RL_ODONTO_APP;
GRANT SELECT ON OWNER_ODONTO.SEQ_AGENDAMENTOS TO RL_ODONTO_APP;
GRANT SELECT ON OWNER_ODONTO.SEQ_PRONTUARIO TO RL_ODONTO_APP;
GRANT SELECT ON OWNER_ODONTO.SEQ_AUDITORIA TO RL_ODONTO_APP;

-- Grants para leitura (Views e Selects basicos)
GRANT SELECT ON OWNER_ODONTO.VW_AGENDA_DIARIA_DENTISTA TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.VW_HISTORICO_PRONTUARIO_PACIENTE TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.VW_PROCEDIMENTOS_MAIS_REALIZADOS TO RL_ODONTO_READONLY;

GRANT SELECT ON OWNER_ODONTO.ESPECIALIDADES TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.DENTISTAS TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.PROCEDIMENTOS TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.PACIENTES TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.AGENDAMENTOS TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.ODONTOGRAMA TO RL_ODONTO_READONLY;
GRANT SELECT ON OWNER_ODONTO.ODONTOGRAMA_PROCEDIMENTOS TO RL_ODONTO_READONLY;
