CREATE SEQUENCE OWNER_ODONTO.SEQ_ESPECIALIDADES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_DENTISTAS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_PACIENTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_PROCEDIMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_AGENDAMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_PRONTUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE OWNER_ODONTO.SEQ_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
