CREATE OR REPLACE VIEW OWNER_ODONTO.VW_PROCEDIMENTOS_MAIS_REALIZADOS AS
SELECT 
    pr.NOME_PROCEDIMENTO,
    e.NOME_ESPECIALIDADE,
    COUNT(pe.ID_PRONTUARIO) AS QTD_REALIZADA,
    SUM(pe.VALOR_COBRADO) AS RECEITA_TOTAL
FROM OWNER_ODONTO.PROCEDIMENTOS pr
JOIN OWNER_ODONTO.ESPECIALIDADES e ON pr.ID_ESPECIALIDADE = e.ID_ESPECIALIDADE
LEFT JOIN OWNER_ODONTO.PRONTUARIO_ELETRONICO pe ON pr.ID_PROCEDIMENTO = pe.ID_PROCEDIMENTO
GROUP BY pr.NOME_PROCEDIMENTO, e.NOME_ESPECIALIDADE
ORDER BY QTD_REALIZADA DESC;
